--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/YourGitHubUsername/nexusfactions

build-by-default: true

projects:
  NexusFactions:
    path: ""
    icon: icon.png
    model: default
    type: plugin
    libs:
      - src: jojoe77777/FormAPI
        version: ^2.0
        shade: single
    
...
